before_install: 
 - sudo apt-get install libzmq3-dev
# - sudo wget -P /usr/local/bin
# https://bitbucket.org/dalloliogm/fake-qsub/raw/default/{b,q}sub
# - sudo chmod a+x /usr/local/bin/{b,q}sub
 - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
 - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
 - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
 - echo "Host localhost
    IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config 

language: r

warnings_are_errors: false

cache: packages
