before_install: 
 - sudo apt-get install libzmq3-dev
 - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
 - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
 - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
 - echo "Host localhost
    IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

before_script:
 - export PATH=$PATH:$PWD/tests/bin

language: r

warnings_are_errors: false

cache: packages
